/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-02-21 06:19:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class more_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("  <script src=\"../resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resources/chat/css/styles.css\">\r\n");
      out.write("  <title>More</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tvar chatScroll = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.chatScroll.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tif(chatScroll == null || chatScroll ==\"\") {\r\n");
      out.write("\t\t\t$(window).scrollTop(0);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(window).scrollTop(chatScroll);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(window).on('beforeunload', function() {\r\n");
      out.write("\t\tvar login = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tif(login == null || login == \"\") {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.cookie = \"chatPage=\" + escape(6) + \"; path=/;\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar currentScroll = $(document).scrollTop();\r\n");
      out.write("\t\tdocument.cookie = \"chatScroll=\" + escape(currentScroll) + \"; path=/;\";\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("  <header class=\"top-header\">\r\n");
      out.write("    <div class=\"header__top\">\r\n");
      out.write("      <div class=\"header__column\">\r\n");
      out.write("        <!-- plane icon -->\r\n");
      out.write("        <i class=\"fa fa-plane\"></i>\r\n");
      out.write("\r\n");
      out.write("        <!-- wifi icon -->\r\n");
      out.write("        <i class=\"fa fa-wifi\"></i>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"header__column\">\r\n");
      out.write("        <span class=\"header__time\">18:38</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"header__column\">\r\n");
      out.write("        <!-- moon icon -->\r\n");
      out.write("        <i class=\"fa fa-moon-o\"></i>\r\n");
      out.write("\r\n");
      out.write("        <!-- blue icon -->\r\n");
      out.write("        <i class=\"fa fa-bluetooth-b\"></i>\r\n");
      out.write("\r\n");
      out.write("        <span class=\"header__battery\">66% <!-- battery icon --><i class=\"fa fa-battery-full\"></i></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"header__bottom\">\r\n");
      out.write("      <div class=\"header__column\">\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"header__column\">\r\n");
      out.write("        <span class=\"header__text\">More</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"header__column\">\r\n");
      out.write("        <i class=\"fa fa-cog fa-lg\"></i>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <main class=\"more\">\r\n");
      out.write("    <header class=\"more__header\">\r\n");
      out.write("      <div class=\"more-header__column\">\r\n");
      out.write("        <img src=\"images/avatar.png\" alt=\"\">\r\n");
      out.write("        <div class=\"more-header__info\">\r\n");
      out.write("          <h3 class=\"more-header__title\">\r\n");
      out.write("            Seungyong Lee\r\n");
      out.write("          </h3>\r\n");
      out.write("          <span class=\"more-header__subtitle\">\r\n");
      out.write("            bongbongco@gmail.com\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <i class=\"fa fa-comment-o fa-2x\"></i>\r\n");
      out.write("    </header>\r\n");
      out.write("    <section class=\"more__options\">\r\n");
      out.write("      <div class=\"more__option\">\r\n");
      out.write("        <i class=\"fa fa-smile-o fa-2x\"></i>\r\n");
      out.write("        <span class=\"more__option-title\">Emoticons</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"more__option\">\r\n");
      out.write("        <i class=\"fa fa-paint-brush fa-2x\"></i>\r\n");
      out.write("        <span class=\"more__option-title\">Themes</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"more__option\">\r\n");
      out.write("        <i class=\"fa fa-hand-peace-o fa-2x\"></i>\r\n");
      out.write("        <span class=\"more__option-title\">Plus Friend</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"more__option\">\r\n");
      out.write("        <i class=\"fa fa-user-circle-o fa-2x\"></i>\r\n");
      out.write("        <span class=\"more__option-title\">Account</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"more__plus-friends\">\r\n");
      out.write("      <header class=\"plus-friends__header\">\r\n");
      out.write("        <h2 class=\"plus-friends__title\">Plus Friends</h2>\r\n");
      out.write("        <span class=\"plus-friends__learn-more\">\r\n");
      out.write("          <i class=\"fa fa-info-circle\"></i>\r\n");
      out.write("          Learn More\r\n");
      out.write("        </span>\r\n");
      out.write("      </header>\r\n");
      out.write("      <div class=\"plus-friends__items\">\r\n");
      out.write("        <div class=\"plus-friends__item\">\r\n");
      out.write("          <i class=\"fa fa-cutlery\"></i>\r\n");
      out.write("          <span class=\"plus-friends__item-title\">Order</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"plus-friends__item\">\r\n");
      out.write("          <i class=\"fa fa-home\"></i>\r\n");
      out.write("          <span class=\"plus-friends__item-title\">Store</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"plus-friends__item\">\r\n");
      out.write("          <i class=\"fa fa-television\"></i>\r\n");
      out.write("          <span class=\"plus-friends__item-title\">TV Channel/Radio...</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"plus-friends__item\">\r\n");
      out.write("          <i class=\"fa fa-pencil\"></i>\r\n");
      out.write("          <span class=\"plus-friends__item-title\">Creation</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"plus-friends__item\">\r\n");
      out.write("          <i class=\"fa fa-graduation-cap\"></i>\r\n");
      out.write("          <span class=\"plus-friends__item-title\">Education</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"plus-friends__item\">\r\n");
      out.write("          <i class=\"fa fa-university\"></i>\r\n");
      out.write("          <span class=\"plus-friends__item-title\">Politics/Society</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"plus-friends__item\">\r\n");
      out.write("          <i class=\"fa fa-krw\"></i>\r\n");
      out.write("          <span class=\"plus-friends__item-title\">Finance</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"plus-friends__item\">\r\n");
      out.write("          <i class=\"fa fa-video-camera\"></i>\r\n");
      out.write("          <span class=\"plus-friends__item-title\">Movies/Music</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"more__links\">\r\n");
      out.write("      <div class=\"more__option\">\r\n");
      out.write("        <img src=\"images/kakaoStory.png\" alt=\"\" class=\"more__options-image\">\r\n");
      out.write("        <span class=\"more__options-title\">Kakao Story</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"more__option\">\r\n");
      out.write("        <img src=\"images/path.png\" alt=\"\" class=\"more__options-image\">\r\n");
      out.write("        <span class=\"more__options-title\">Path</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"more__option\">\r\n");
      out.write("        <img src=\"images/kakaoFriends.png\" alt=\"\" class=\"more__options-image\">\r\n");
      out.write("        <span class=\"more__options-title\">Kakao friends</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </main>\r\n");
      out.write("  <nav class=\"tab-bar\">\r\n");
      out.write("    <a href=\"javascript:location.replace('../chat/friend.do')\" class=\"tab-bar__tab\">\r\n");
      out.write("      <i class=\"fa fa-user\"></i>\r\n");
      out.write("      <span class=\"tab-bar__title\">Friends</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a href=\"javascript:location.replace('../chat/chats.do')\" class=\"tab-bar__tab\">\r\n");
      out.write("      <i class=\"fa fa-comment\"></i>\r\n");
      out.write("      <span class=\"tab-bar__title\">Chats</span>\r\n");
      out.write("    </a>\r\n");
      out.write("      <a href=\"javascript:location.replace('../chat/find.do')\" class=\"tab-bar__tab\">\r\n");
      out.write("      <i class=\"fa fa-search\"></i>\r\n");
      out.write("      <span class=\"tab-bar__title\">Find</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a href=\"javascript:location.replace('../chat/more.do')\" class=\"tab-bar__tab tab-bar__tab--selected\">\r\n");
      out.write("      <i class=\"fa fa-ellipsis-h\"></i>\r\n");
      out.write("      <span class=\"tab-bar__title\">More</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <div class=\"bigScreenText\">\r\n");
      out.write("    Please make your screen smaller\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
